
<style>
.remark-slide table {border-top: 0; border-bottom: 0;}
th, td {padding: 10px; padding-left: 16px; padding-right: 16px; padding-top: 14px;}
.bluecode code {font-weight: 700}   
.split-table hr {border-top: 1px dashed gray; width: 100% !important; margin-top: 14px; margin-bottom: 2px; margin-left: 0;}
</style>

<div class="bluecode" style="font-size: 1.1rem; width: 78%; margin-top: 44px; margin-left: auto; margin-right: auto; font-weight: 700;">

```{r, results='asis', echo=F, warning=F, message=F}
library(dplyr)
library(kableExtra)

tools <- tibble::tribble(
~Function, ~Job,
"filter()", "Keep rows that pass your tests",
"select()", "Select columns to keep or drop",  
"arrange()", "Sort a table based on a column's values",  
"mutate()", "Add new columns or update existing columns", 
"summarize()", "Get summary statistics for an entire table",   
"group_by()", "Group data for group specific summaries"
)

tools <- tools %>% 
  mutate(Function = paste("<code>", Function, "  </code>"))


tools[1:4, ] %>% kable(format = "html", escape = F, align = c("c","l","l"))
```

</div>

<div class="split-table">
<hr>
</div>

<div class="tealcode" style="font-size: 1.7rem; width: 82%; margin-top: 0;  font-weight: 700; margin-left: auto; margin-right: auto;">

```{r, results='asis', echo=F, warning=F, message=F}
tools[5:6, ] %>% 
  kable(format = "html", escape = F, align = c("c","l","l"), col.names = NULL)
                      
```

</div>
